# Generated by Django 5.0.4 on 2024-05-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SWAG_basic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="other_role",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
