# Generated by Django 5.0.4 on 2024-05-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SWAG_basic", "0002_volunteer_other_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="date_created",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="date_created"
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="date_created",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="date_created"
            ),
        ),
    ]
