# Generated by Django 5.0.4 on 2024-04-07 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("product_name", models.CharField(max_length=500)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("picture", models.ImageField(null=True, upload_to="uploads/")),
            ],
            options={"verbose_name_plural": "Product", "db_table": "Product",},
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "payment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tx_ref", models.CharField(max_length=500)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("quantity", models.IntegerField()),
                ("status", models.CharField(max_length=500)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date_created"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Payments", "db_table": "Payments",},
        ),
    ]
