# Generated by Django 5.0.4 on 2024-05-01 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SWAG_payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="States",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=500)),
            ],
            options={"verbose_name_plural": "States", "db_table": "States",},
        ),
        migrations.CreateModel(
            name="Schools",
            fields=[
                (
                    "school_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("school_name", models.CharField(max_length=500)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SWAG_payment.states",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Schools", "db_table": "School",},
        ),
    ]
