# Generated by Django 5.0.4 on 2024-04-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SWAG_payment", "0002_paymentreceipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreceipt",
            name="status",
            field=models.CharField(default="pending", max_length=500),
        ),
    ]
