# Generated by Django 5.0.4 on 2024-04-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SWAG_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
